steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/skripsi-113/facedetec-apps-repo", "."]
  # Push the container image to Container Registry
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/skripsi-113/facedetec-apps-repo"]

images: 
  - gcr.io/skripsi-113/facedetec-apps-repo
