steps:
- name: 'docker'
  args: [ 'buildx', 'create', '--name', 'mybuilder', '--use' ]
- name: 'docker'
  args: [ 'buildx', 'build', '--platform', 'linux/arm64', '-t', 'us-docker.pkg.dev/gke-autopilot-test/facedetec-apps-repo', '--push', '.', ]