steps:
  # Build the container image
  - name: "docker"
    args: [ 'buildx', 'create', '--name', 'mabuilder', '--use' ]
  # Push the container image to Container Registry
  - name: 'docker'
    args: [ 'buildx', 'build', '--platform', 'linux/arm64', '-t', 'us-central1-docker.pkg.dev/gke-autopilot-test/test/face-detec-repos', '--push', '.',]

